### ISSUE TITLE
Error in similarity_map

### ISSUE THREAD

**Issue by OdessyLiu** [michaelgavin/litmath#1]
Hi Michael,

I just read your book _Literary Mathematics_ and am trying to reproduce your results in the book following your instruction on your website (https://literarymathematics.org/computation-of-meaning/). When I was doing the result of your second chapter, computation of meaning, and reached the step drawing the similarity map, I got an error saying: 

```
library(litmath)
library(litmathdata)
data(kwic)
M <- ppmi(kwic)
similarity_map(M, "foot")

Error in if (class(mat) == "docMatrix") { : the condition has length > 1
```
I went back to your original code of similarity_map and found the error happened in the the first few lines:

```
similarity_map = function(mat, 
                          keyword, 
                          method = "cosine", 
                          margin = 1,
                          numResults = 40, 
                          numGrps = 5) {
  if (class(mat) == "docMatrix") {
    mat = mat@mat
  }
```

I tried to check the class type of M, and it was "Matrix" "array" no matter what I do:

```
> M <- as.matrix(M)
> if (identical(class(M), "docMatrix")) {
+   print("yes")
+ } else {
+   print(class(M))
+ }
[1] "matrix" "array" 
```

May I kindly ask what should I do to jumpthrough this error? Thank you.

**Comment by michaelgavin** [comment]
If you reinstall 'litmath' it should work now. There were a couple little dependencies hidden away in the code that I hadn't cleared out. (The "docMatrix" data format was used in another R package that is no longer supported, but was installed on an old machine.) Let me know if you have any more issues. --- with new versions of ggplot2 you might see errors reported when making the graphics, but the PCA maps still work fine, the hierarchical clustering just doesn't display properly. So if your version of ggplot is brand new, the pretty little coloring won't display the semantic groups. I don't have a solution for that, yet. If you'd like me to look at it, just open a new issue. Or even better you can also just email me with questions.
